[pytest]
testpaths = tests
filterwarnings =
    error
    ignore:.*pkg_resources.*:DeprecationWarning
    ignore:.*declare_namespace.*:DeprecationWarning
    ignore:.*googleapiclient.*:DeprecationWarning
    ignore:.*urllib3.*:Warning
